version: 0.0
os: linux
files:
  - source: /RealEstateLoanApplication.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start.sh
      timeout: 300
      runas: root