version: 0.1
phases:
  build:
    commands: 
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
  post_build:
    commands: 
      - echo Build successful...
artifacts:
  files:
    - target/real-estate-loan-application
  discard-paths: 'yes'
