version: 0.2
phases:
  build:
    install:
      runtime-versions:
        java: corretto17
    commands: 
      - echo Entered the build phase...
      - echo Build started on `date`
      - java -version
      - mvn package
  post_build:
    commands: 
      - echo Build successful...
artifacts:
  files:
    - real-estate-loan-application
  discard-paths: 'yes'
